#-------------------------------
# Site Settings
title: Lexie Wang
logo: #'/images/logo-lx.png'
author: Lexie Wang
description: This is Lexie's personal website.


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Contact'
      url: '/contact/'


#-------------------------------
# Hero Settings
hero:
  hero__title: Hello, my name’s Lexie.
  hero__description: I recently graduated from University of California, Santa Barbara with a BA degree in Linguistics (Language and Speech Technologies Emphasis) and Communication. I'm currently based in Dalian, China. My pronouns are she/her/hers.


#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Gallery
  portfolio__gallery:
    - image: /images/image-cert-01.png
      title: Algorithmic Toolbox Coursera Certificate
      description: Verify this certificate <a href="https://coursera.org/share/de9dbde95c8aa0836eae75ba63d5b8bc">Coursera</a>

    - image: /images/img-cert-03.png
      title: Data Structures Coursera Certificate
      description: Verify this certificate <a href="https://coursera.org/share/706f1657f83b19a53387316360de3b7a">Coursera</a>

    - image: /images/img-cert-02.png
      title: Bayesian Statistics Coursera Certificate
      description: Verify this certificate <a href="https://coursera.org/share/3d50464630cbc42f97567292d86dbeb5">Coursera</a>

    - image: /images/img-cert-06.png
      title: Machine Learning Foundations Coursera Certificate
      description: Verify this certificate <a href="https://coursera.org/verif y/THBJ7SAT7APF">Coursera</a>

    - image: /images/img-cert-04.png
      title: Blockchain Basics Coursera Certificate
      description: Verify this certificate <a href="https://www.coursera.org/account/accomplishments/verify/VNECSTVMQZJK">Coursera</a>

    - image: /images/img-cert-05.png
      title: Smart Contracts Coursera Certificate
      description: Verify this certificate <a href="https://coursera.org/verif y/GVHMBQ4ZZRQ7">Coursera</a>

    - image: /images/img-code-02.png
      title: Java Coding Projects
      description: Java practice projects can be found on <a href="https://github.com/lexiewangdl/java-practice">GitHub</a>




#-------------------------------
# Footer Settings
social:
# - {icon: "ion-logo-twitter", color: "#55acee", label: Twitter, link: "https://twitter.com"}
- {icon: "ion-logo-linkedin", color: "#0077b5", label: Linkedin, link: "https://www.linkedin.com/in/chenyue-wang-51073b225/"}
# - {icon: "ion-logo-pinterest", color: "#bd081c", label: Pinterest, link: "https://pinterest.com"}
# - {icon: "ion-md-book", color: "#fe0000", label: RED, link: "https://www.xiaohongshu.com/user/profile/557d11b941a2b35a959984ae?xhsshare=WeixinSession&appuid=557d11b941a2b35a959984ae&apptime=1638615764"}
- {icon: "ion-logo-github", color: "#211f1f", label: GitHub, link: "https://github.com/lexiewangdl"}
- {icon: "ion-md-code", color: "#f4bd48", label: LeetCode, link: "https://leetcode.com/lexiewang/"}

# Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: chenyuewang@ucsb.edu # Add your email for contact form
#  description: Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.